### ISSUE TITLE
Turtles dont render correctly.

### ISSUE THREAD

**Issue by matty45** [mystiacraft/cc-tweaked-fabric#1] opened 2019-08-10 01:49 UTC
https://i.imgur.com/v5p9lGx.png

For some reason the turtles appear to be missing textures when placed.

**Comment by parly** [comment] 2019-08-10 02:37
Hello, thank you for reporting the bug!

Are you using OptiFabric by any chance? I'm currently looking for a workaround in that case...

**Comment by matty45** [comment] 2019-08-10 02:38
Ah, that must be the problem! ill turn optifabric off and see if that fixes anything

**Comment by matty45** [comment] 2019-08-10 02:42
Yup! it was optifine/optifabric.

**Comment by parly** [comment] 2019-08-10 02:55
Thanks for sharing the result! I'll continue investigating this issue.

**Comment by Eliteneet** [comment] 2019-09-27 06:54
Was there any headway on this issue? Facing the same problem on the latest version.

**Comment by parly** [comment] 2019-09-27 13:37
I have finally identified the cause, so now working on a fix for this. I should be able to release it in a few hours.

**Closed** 2019-09-27 14:36 UTC

**Comment by parly** [comment] 2019-09-27 15:31
Fixed in 1.83.2+build.5. If the problem persists, please let me know by reopening this issue or creating a new one.
